title: "Squid Programming Guide"
description: "Squid Web Cache code reference"
url: "https://code-reference-cache.org"
plugins:
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-titles-from-headings
#  - jekyll-sitemap
