title: "Squid Programming Guide"
description: "Squid Web Cache programmers' guide"
url: "https://programming-guide.squid-cache.org/"
plugins:
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-titles-from-headings

# - jekyll-sitemap
